try {
  val results = try {
    val x = 0
  } catch {
    case e: Exception =>
      throw new Exception("")
  }
} finally {
    println("Hi")
}
-----
0(1) element: None
1(2,8) element: TryStatement
2(3,4) element: TryStatement
3(7) VAL x
4(5) element: CatchBlock
5(6) VAL e
6() element: ThrowStatement
7(8,10) VAL results
8(9) element: FinallyBlock
9() READ println
10() element: None